
-- Identify the average delivery time per month between the last 3 years

SELECT YEAR(ORDERS.OrderDate) AS YEAR, MONTH(ORDERS.ORDERDATE) AS MONTH, AVG(DATEDIFF(DAY, ORDERS.ORDERDATE, ORDERS.SHIPPEDDATE)) AS AVG_DELIVERY_TIME
FROM Orders
WHERE ORDERS.ShippedDate IS NOT NULL
GROUP BY YEAR(ORDERS.OrderDate), MONTH(ORDERS.ORDERDATE)
ORDER BY YEAR(ORDERS.OrderDate) ASC, MONTH(ORDERS.ORDERDATE) ASC;